providers = ['...', 'python']

[phases.install]
 cmds=["...", "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements-api.txt"]

[start]
  cmd="uvicorn api:app --host 0.0.0.0 --port $PORT"
