providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1678147396'

[variables]
NIXPACKS_METADATA = 'python,postgres'
PYTHONUNBUFFERED = '1'

[phases.install]
dependsOn = ['setup']
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements-api.txt']
cacheDirectories = ['/root/.cache/pip']
paths = ['/opt/venv/bin']

[phases.setup]
aptPkgs = ['...', 'libgl1']
nixPkgs = [
    'python310',
    'postgresql',
    'gcc',
]
nixLibs = [
    'zlib',
    'stdenv.cc.cc.lib',
]
nixOverlays = []
nixpkgsArchive = '293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847'

[start]
cmd="python worker/traffic.py"
